package DAO;
// Generated Jul 12, 2016 2:30:37 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Comments generated by hbm2java
 */
@Entity
@Table(name = "comments", catalog = "taskmanager")
public class Comments implements java.io.Serializable {

	private Integer idCommm;
	private Date dataCom;
	private String content;
	private int idCommTask;
	private int idCommUser;

	public Comments() {
	}

	public Comments(Date dataCom, String content, int idCommTask, int idCommUser) {
		this.dataCom = dataCom;
		this.content = content;
		this.idCommTask = idCommTask;
		this.idCommUser = idCommUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_commm", unique = true, nullable = false)
	public Integer getIdCommm() {
		return this.idCommm;
	}

	public void setIdCommm(Integer idCommm) {
		this.idCommm = idCommm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_com", nullable = false, length = 19)
	public Date getDataCom() {
		return this.dataCom;
	}

	public void setDataCom(Date dataCom) {
		this.dataCom = dataCom;
	}

	@Column(name = "content", nullable = false, length = 500)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "id_comm_task", nullable = false)
	public int getIdCommTask() {
		return this.idCommTask;
	}

	public void setIdCommTask(int idCommTask) {
		this.idCommTask = idCommTask;
	}

	@Column(name = "id_comm_user", nullable = false)
	public int getIdCommUser() {
		return this.idCommUser;
	}

	public void setIdCommUser(int idCommUser) {
		this.idCommUser = idCommUser;
	}

}
