package DAO;
// Generated Jul 12, 2016 2:30:37 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DetaliProject generated by hbm2java
 */
@Entity
@Table(name = "detali_project", catalog = "taskmanager")
public class DetaliProject implements java.io.Serializable {

	private Integer idDetaliProj;
	private int idDetaliProjUser;
	private int idDetaliProjProj;

	public DetaliProject() {
	}

	public DetaliProject(int idDetaliProjUser, int idDetaliProjProj) {
		this.idDetaliProjUser = idDetaliProjUser;
		this.idDetaliProjProj = idDetaliProjProj;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_detali_proj", unique = true, nullable = false)
	public Integer getIdDetaliProj() {
		return this.idDetaliProj;
	}

	public void setIdDetaliProj(Integer idDetaliProj) {
		this.idDetaliProj = idDetaliProj;
	}

	@Column(name = "id_detali_proj_user", nullable = false)
	public int getIdDetaliProjUser() {
		return this.idDetaliProjUser;
	}

	public void setIdDetaliProjUser(int idDetaliProjUser) {
		this.idDetaliProjUser = idDetaliProjUser;
	}

	@Column(name = "id_detali_proj_proj", nullable = false)
	public int getIdDetaliProjProj() {
		return this.idDetaliProjProj;
	}

	public void setIdDetaliProjProj(int idDetaliProjProj) {
		this.idDetaliProjProj = idDetaliProjProj;
	}

}
