package DAO;
// Generated Jul 12, 2016 2:30:37 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Prioritities generated by hbm2java
 */
@Entity
@Table(name = "prioritities", catalog = "taskmanager")
public class Prioritities implements java.io.Serializable {

	private Integer idPriority;
	private String level;

	public Prioritities() {
	}

	public Prioritities(String level) {
		this.level = level;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_priority", unique = true, nullable = false)
	public Integer getIdPriority() {
		return this.idPriority;
	}

	public void setIdPriority(Integer idPriority) {
		this.idPriority = idPriority;
	}

	@Column(name = "level", nullable = false, length = 50)
	public String getLevel() {
		return this.level;
	}

	public void setLevel(String level) {
		this.level = level;
	}

}
