package DAO;
// Generated Jul 12, 2016 2:30:37 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", catalog = "taskmanager")
public class Project implements java.io.Serializable {

	private Integer idProject;
	private String title;
	private String description;
	private int idProjectRelease;
	private int idProjectUser;

	public Project() {
	}

	public Project(String title, String description, int idProjectRelease, int idProjectUser) {
		this.title = title;
		this.description = description;
		this.idProjectRelease = idProjectRelease;
		this.idProjectUser = idProjectUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_project", unique = true, nullable = false)
	public Integer getIdProject() {
		return this.idProject;
	}

	public void setIdProject(Integer idProject) {
		this.idProject = idProject;
	}

	@Column(name = "title", nullable = false, length = 200)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "description", nullable = false, length = 500)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "id_project_release", nullable = false)
	public int getIdProjectRelease() {
		return this.idProjectRelease;
	}

	public void setIdProjectRelease(int idProjectRelease) {
		this.idProjectRelease = idProjectRelease;
	}

	@Column(name = "id_project_user", nullable = false)
	public int getIdProjectUser() {
		return this.idProjectUser;
	}

	public void setIdProjectUser(int idProjectUser) {
		this.idProjectUser = idProjectUser;
	}

}
