package DAO;
// Generated Jul 12, 2016 2:30:37 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Release generated by hbm2java
 */
@Entity
@Table(name = "release", catalog = "taskmanager")
public class Release implements java.io.Serializable {

	private Integer idRelease;
	private Date dataRelease;
	private String versiunea;
	private int idReleaseProject;

	public Release() {
	}

	public Release(Date dataRelease, String versiunea, int idReleaseProject) {
		this.dataRelease = dataRelease;
		this.versiunea = versiunea;
		this.idReleaseProject = idReleaseProject;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_release", unique = true, nullable = false)
	public Integer getIdRelease() {
		return this.idRelease;
	}

	public void setIdRelease(Integer idRelease) {
		this.idRelease = idRelease;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "data_release", nullable = false, length = 19)
	public Date getDataRelease() {
		return this.dataRelease;
	}

	public void setDataRelease(Date dataRelease) {
		this.dataRelease = dataRelease;
	}

	@Column(name = "versiunea", nullable = false, length = 200)
	public String getVersiunea() {
		return this.versiunea;
	}

	public void setVersiunea(String versiunea) {
		this.versiunea = versiunea;
	}

	@Column(name = "id_release_project", nullable = false)
	public int getIdReleaseProject() {
		return this.idReleaseProject;
	}

	public void setIdReleaseProject(int idReleaseProject) {
		this.idReleaseProject = idReleaseProject;
	}

}
