package DAO;
// Generated Jul 12, 2016 2:30:37 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "task", catalog = "taskmanager")
public class Task implements java.io.Serializable {

	private Integer idTask;
	private String taskName;
	private String taskDescription;
	private int idTaskRelease;
	private int idTaskPriority;
	private int idTaskStatus;
	private int idTaskProject;
	private int idTaskCreator;
	private int idTaskDesigner;
	private int idTaskImplemet;
	private int idTaskTester;

	public Task() {
	}

	public Task(String taskName, String taskDescription, int idTaskRelease, int idTaskPriority, int idTaskStatus,
			int idTaskProject, int idTaskCreator, int idTaskDesigner, int idTaskImplemet, int idTaskTester) {
		this.taskName = taskName;
		this.taskDescription = taskDescription;
		this.idTaskRelease = idTaskRelease;
		this.idTaskPriority = idTaskPriority;
		this.idTaskStatus = idTaskStatus;
		this.idTaskProject = idTaskProject;
		this.idTaskCreator = idTaskCreator;
		this.idTaskDesigner = idTaskDesigner;
		this.idTaskImplemet = idTaskImplemet;
		this.idTaskTester = idTaskTester;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_task", unique = true, nullable = false)
	public Integer getIdTask() {
		return this.idTask;
	}

	public void setIdTask(Integer idTask) {
		this.idTask = idTask;
	}

	@Column(name = "task_name", nullable = false, length = 200)
	public String getTaskName() {
		return this.taskName;
	}

	public void setTaskName(String taskName) {
		this.taskName = taskName;
	}

	@Column(name = "task_description", nullable = false, length = 500)
	public String getTaskDescription() {
		return this.taskDescription;
	}

	public void setTaskDescription(String taskDescription) {
		this.taskDescription = taskDescription;
	}

	@Column(name = "id_task_release", nullable = false)
	public int getIdTaskRelease() {
		return this.idTaskRelease;
	}

	public void setIdTaskRelease(int idTaskRelease) {
		this.idTaskRelease = idTaskRelease;
	}

	@Column(name = "id_task_priority", nullable = false)
	public int getIdTaskPriority() {
		return this.idTaskPriority;
	}

	public void setIdTaskPriority(int idTaskPriority) {
		this.idTaskPriority = idTaskPriority;
	}

	@Column(name = "id_task_status", nullable = false)
	public int getIdTaskStatus() {
		return this.idTaskStatus;
	}

	public void setIdTaskStatus(int idTaskStatus) {
		this.idTaskStatus = idTaskStatus;
	}

	@Column(name = "id_task_project", nullable = false)
	public int getIdTaskProject() {
		return this.idTaskProject;
	}

	public void setIdTaskProject(int idTaskProject) {
		this.idTaskProject = idTaskProject;
	}

	@Column(name = "id_task_creator", nullable = false)
	public int getIdTaskCreator() {
		return this.idTaskCreator;
	}

	public void setIdTaskCreator(int idTaskCreator) {
		this.idTaskCreator = idTaskCreator;
	}

	@Column(name = "id_task_designer", nullable = false)
	public int getIdTaskDesigner() {
		return this.idTaskDesigner;
	}

	public void setIdTaskDesigner(int idTaskDesigner) {
		this.idTaskDesigner = idTaskDesigner;
	}

	@Column(name = "id_task_implemet", nullable = false)
	public int getIdTaskImplemet() {
		return this.idTaskImplemet;
	}

	public void setIdTaskImplemet(int idTaskImplemet) {
		this.idTaskImplemet = idTaskImplemet;
	}

	@Column(name = "id_task_tester", nullable = false)
	public int getIdTaskTester() {
		return this.idTaskTester;
	}

	public void setIdTaskTester(int idTaskTester) {
		this.idTaskTester = idTaskTester;
	}

}
