package DAO;
// Generated Jul 12, 2016 2:30:37 PM by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "taskmanager")
public class User implements java.io.Serializable {

	private Integer idUser;
	private String user;
	private String password;
	private int idRolUser;

	public User() {
	}

	public User(String user, String password, int idRolUser) {
		this.user = user;
		this.password = password;
		this.idRolUser = idRolUser;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id_user", unique = true, nullable = false)
	public Integer getIdUser() {
		return this.idUser;
	}

	public void setIdUser(Integer idUser) {
		this.idUser = idUser;
	}

	@Column(name = "user", nullable = false, length = 200)
	public String getUser() {
		return this.user;
	}

	public void setUser(String user) {
		this.user = user;
	}

	@Column(name = "password", nullable = false, length = 200)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "id_rol_user", nullable = false)
	public int getIdRolUser() {
		return this.idRolUser;
	}

	public void setIdRolUser(int idRolUser) {
		this.idRolUser = idRolUser;
	}

}
